import jsPDF from "jspdf";

export function generateReport(item) {

    const doc = new jsPDF();

    // ===============================
    // COVER PAGE
    // ===============================

    doc.setFillColor(22, 101, 52);
    doc.rect(0, 0, 210, 297, "F");

    // Title
    doc.setFontSize(30);
    doc.setTextColor(255, 255, 255);
    doc.text("AGRIVISION", 105, 60, { align: "center" });

    // Subtitle
    doc.setFontSize(18);
    doc.text(
        "AI Crop Disease Detection Report",
        105,
        75,
        { align: "center" }
    );

    // Decorative Line
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.7);
    doc.line(45, 85, 165, 85);

    // Small Description
    doc.setFontSize(13);

    doc.text(
        "Generated Automatically",
        105,
        105,
        { align: "center" }
    );

    doc.text(
        new Date().toLocaleString(),
        105,
        118,
        { align: "center" }
    );

    // Bottom Text
    doc.setFontSize(11);

    doc.text(
        "Smart Agriculture using Artificial Intelligence",
        105,
        270,
        { align: "center" }
    );

    // Second Page
    doc.addPage();

    // ===========================
    // HEADER
    // ===========================

    doc.setFillColor(34, 197, 94);
    doc.rect(0, 0, 210, 28, "F");

    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);

    doc.text("AGRIVISION", 20, 15);

    doc.setFontSize(12);

    doc.text("AI Crop Disease Report", 20, 23);

    // ===========================
    // DATE
    // ===========================

    doc.setTextColor(0, 0, 0);

    let y = 40;

    doc.setFontSize(12);

    doc.text(
        `Generated : ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 15;

    // ===========================
    // IMAGE
    // ===========================

    if (item.image) {

        try {

            doc.addImage(
                item.image,
                "JPEG",
                20,
                y,
                70,
                70
            );

        } catch (e) { }

    }

    y += 80;

    // ===========================
    // DISEASE INFO
    // ===========================

    doc.setFillColor(220, 245, 225);
    doc.roundedRect(15, y - 6, 180, 12, 3, 3, "F");

    doc.setTextColor(22, 101, 52);
    doc.setFontSize(16);

    doc.text("Disease Information", 20, y + 2);

    y += 15;

    doc.setTextColor(0, 0, 0);

    let diseaseColor = [0, 180, 0];

    if (item.status === "Disease")
        diseaseColor = [220, 38, 38];

    doc.setFillColor(...diseaseColor);

    doc.roundedRect(20, y - 8, 60, 10, 2, 2, "F");

    doc.text(
        item.disease.replaceAll("_", " "),
        50,
        y - 1,
        { align: "center" }
    );

    doc.setTextColor(0, 0, 0);

    y += 8;

    doc.text(`Confidence : ${Number(item.confidence).toFixed(1)}%`, 20, y);

    y += 8;

    doc.text(`Status : ${item.status}`, 20, y);

    y += 8;

    doc.text(`Leaves Detected : ${item.leaf_count}`, 20, y);

    y += 20;

    // ===========================
    // RECOMMENDED ACTION
    // ===========================

    doc.setFillColor(230, 245, 255);
    doc.roundedRect(15, y - 6, 180, 12, 3, 3, "F");

    doc.setTextColor(0, 90, 180);
    doc.setFontSize(16);

    doc.text("Recommended Action", 20, y + 2);

    y += 15;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    const actions = [

        item.recommendation,

        "Monitor the infected plant every 5-7 days.",

        "Remove severely infected leaves if required.",

        "Avoid spraying during heavy rain or strong wind.",

        "Continue regular field inspection."

    ];

    actions.forEach(action => {

        doc.text(`• ${action}`, 22, y);

        y += 8;

    });

    // ===========================
    // CONFIDENCE BAR
    // ===========================

    doc.setFillColor(220, 220, 220);
    doc.roundedRect(20, y, 90, 5, 2, 2, "F");

    doc.setFillColor(34, 197, 94);

    doc.roundedRect(
        20,
        y,
        item.confidence * 0.9,
        5,
        2,
        2,
        "F"
    );

    y += 12;

    y += 5;

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        "Generated automatically by AgriVision",
        20,
        y
    );

    const pages = doc.getNumberOfPages();

    for (let i = 1; i <= pages; i++) {

        doc.setPage(i);

        doc.setDrawColor(200);

        doc.line(15, 285, 195, 285);

        doc.setFontSize(9);

        doc.setTextColor(120);

        doc.text(
            "Generated by AgriVision",
            20,
            291
        );

        doc.text(
            `Page ${i} of ${pages}`,
            175,
            291
        );

    }

    doc.save(`AgriVision_Report_${Date.now()}.pdf`);

}